# Generated by Django 4.0.2 on 2022-02-10 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_employees_date_employees_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='employees',
            new_name='Employee',
        ),
    ]
